name: check
on:
  pull_request:
    branches: [main]
    paths:
      - "cms/**"
      - ".github/workflows/cms-check.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-cms-check
  cancel-in-progress: true
jobs:
  cms-build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: ./cms/
          load: true
          cache-from: type=gha,scope=cms
          cache-to: type=gha,mode=max,scope=cms
